package com.yj.springboot3;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
/**
 *
 * `@SpringBootApplication` 是一个组合注解，它包含了以下三个注解：
 *
 * `@Configuration`：表示该类是一个配置类，用于定义 Spring Boot 应用的配置信息。
 * `@EnableAutoConfiguration`：表示启用 Spring Boot 自动配置功能，根据项目中的依赖自动配置相应的组件。
 * `@ComponentScan`：表示扫描指定包及其子包下的所有组件，并将它们注册到 Spring 容器中。
 * 因此，`@SpringBootApplication` 的作用是创建一个基于 Spring Boot 的应用，并自动配置相关的组件和扫描指定的包。
 */
@SpringBootApplication
public class SpringBoot30002AnnotationApplication {

    public static void main(String[] args) {
        SpringApplication.run(SpringBoot30002AnnotationApplication.class, args);
    }

}
